enum RoutineTaskPurpose {
  RoutineTaskPurpose_GetSubShelf
  RoutineTaskPurpose_CreateSubShelf
  RoutineTaskPurpose_UpdateSubShelf
  RoutineTaskPurpose_DeleteSubShelf
  RoutineTaskPurpose_GetBlockPack
  RoutineTaskPurpose_CreateBlockPack
  RoutineTaskPurpose_UpdateBlockPack
  RoutineTaskPurpose_DeleteBlockPack
  RoutineTaskPurpose_GetRoutine
  RoutineTaskPurpose_CreateRoutine
  RoutineTaskPurpose_UpdateRoutine
  RoutineTaskPurpose_DeleteRoutine
  RoutineTaskPurpose_GetMaterial
  RoutineTaskPurpose_CreateMaterial
  RoutineTaskPurpose_UpdateMaterial
  RoutineTaskPurpose_DeleteMaterial
}
