export type MigrationEntry = {
  idx: number;
  tag: string;
  versionNumber: number;
  sqlContent: string;
  statements: string[];
};

export type MigrationResult = {
  appliedTags: string[];
  finalVersion: number;
};

export type LocalDBMigratorClient = {
  transaction: <T>(
    operation: (transaction: {
      run: (query: string) => Promise<unknown>;
    }) => Promise<T>
  ) => Promise<T>;
};

const normalizeVersionNumber = (version: number | null | undefined): number => {
  if (version === null || version === undefined) return 0;
  if (!Number.isFinite(version)) return 0;
  return Math.max(0, Math.trunc(version));
};

export const splitSqlStatements = (sqlContent: string): string[] => {
  if (sqlContent.includes("--> statement-breakpoint")) {
    return sqlContent
      .split("--> statement-breakpoint")
      .map(statement => statement.trim())
      .filter(Boolean);
  }

  const statements: string[] = [];
  let statementStart = 0;
  let quote: "'" | '"' | "`" | null = null;

  for (let index = 0; index < sqlContent.length; index += 1) {
    const character = sqlContent[index];
    if (quote !== null) {
      if (character === quote) {
        if (sqlContent[index + 1] === quote) {
          index += 1;
        } else {
          quote = null;
        }
      }
      continue;
    }

    if (character === "'" || character === '"' || character === "`") {
      quote = character;
      continue;
    }

    if (character === ";") {
      const statement = sqlContent.slice(statementStart, index).trim();
      if (statement) statements.push(statement);
      statementStart = index + 1;
    }
  }

  const trailingStatement = sqlContent.slice(statementStart).trim();
  if (trailingStatement) statements.push(trailingStatement);
  return statements;
};

const normalizeStatement = (statement: string): string =>
  statement
    // keep migration files generated by drizzle-kit untouched.
    // sqlocal cannot bind placeholders in raw SQL files, so normalize
    // static boolean partial-index predicates to literal values.
    .replace(/("UserTable"\."is_logged_in")\s*=\s*\?/g, "$1 = 1")
    .replace(/("UsersToShelvesTable"\."permission")\s*=\s*\?/g, "$1 = 'Owner'")
    .replace(
      /("UsersToStationsTable"\."permission")\s*=\s*\?/g,
      "$1 = 'Owner'"
    );

export class LocalDBMigrator {
  private runningMigrationPromise: Promise<MigrationResult> | null = null;
  private readonly localDB: LocalDBMigratorClient;
  private readonly migrations: MigrationEntry[] | null;

  constructor(
    localDB: LocalDBMigratorClient,
    migrations: MigrationEntry[] | null = null
  ) {
    this.localDB = localDB;
    this.migrations = migrations;
  }

  private runStatementsWithVersion = async (
    statements: string[],
    targetVersion: number
  ): Promise<void> => {
    await this.localDB.transaction(async transaction => {
      for (const statement of statements) {
        await transaction.run(normalizeStatement(statement));
      }

      await transaction.run(`PRAGMA user_version = ${targetVersion}`);
      const result = await transaction.run(`PRAGMA user_version`);
      const row = Array.isArray(result) ? result[0] : undefined;
      const persistedVersion = normalizeVersionNumber(
        Number(
          row !== null && typeof row === "object"
            ? (row as { user_version?: unknown }).user_version
            : undefined
        )
      );
      if (persistedVersion !== targetVersion) {
        throw new Error(
          `local database migration stopped at version ${persistedVersion}; expected ${targetVersion}.`
        );
      }
    });
  };

  public bootstrapCurrentSchema = async (
    sqlContent: string,
    targetVersion: number,
    tag = "bootstrap-current"
  ): Promise<MigrationResult> => {
    const safeTargetVersion = normalizeVersionNumber(targetVersion);
    await this.runStatementsWithVersion(
      splitSqlStatements(sqlContent),
      safeTargetVersion
    );

    return { appliedTags: [tag], finalVersion: safeTargetVersion };
  };

  // get the largest migration number from the migration files in apps/web/src/api/local/migrations/
  // but return the largest migration number + 1 as the latest version since the user_version from SQLite PRAGMA forced to start from 0
  public getLatestMigrationVersion = (): number => {
    const orderedMigrations = this.migrations ?? [];
    const latestMigration = orderedMigrations[orderedMigrations.length - 1];
    if (!latestMigration) return 0;
    return latestMigration.versionNumber + 1;
  };

  public ensureMigrated = async (options?: {
    currentVersion?: number | null;
    targetVersion?: number | null;
  }): Promise<MigrationResult> => {
    if (this.runningMigrationPromise) return this.runningMigrationPromise;

    this.runningMigrationPromise = (async () => {
      const orderedMigrations = this.migrations ?? [];
      const currentVersionNumber = normalizeVersionNumber(
        options?.currentVersion
      );
      const targetVersionNumber =
        options?.targetVersion === undefined || options?.targetVersion === null
          ? Number.POSITIVE_INFINITY
          : normalizeVersionNumber(options.targetVersion);

      if (currentVersionNumber > targetVersionNumber) {
        throw new Error(
          `local database version ${currentVersionNumber} is newer than target version ${targetVersionNumber}`
        );
      }

      const pendingMigrations = orderedMigrations.filter(migration => {
        const migrationVersion = migration.versionNumber + 1;
        if (migrationVersion <= currentVersionNumber) return false;
        if (migrationVersion > targetVersionNumber) return false;
        return true;
      });

      const appliedTags: string[] = [];
      for (const migration of pendingMigrations) {
        await this.runStatementsWithVersion(
          migration.statements,
          migration.versionNumber + 1
        );
        appliedTags.push(migration.tag);
      }

      const finalVersionNumber =
        pendingMigrations.length > 0
          ? pendingMigrations[pendingMigrations.length - 1].versionNumber + 1
          : currentVersionNumber;

      return {
        appliedTags,
        finalVersion: finalVersionNumber,
      };
    })().finally(() => {
      this.runningMigrationPromise = null;
    });

    return this.runningMigrationPromise;
  };
}
