fragment FragmentedBasicPrivateRoutine on PrivateRoutine {
  id
  stationId
  title
  description
  status
  phase
  isPinned
  scheduledStartAt
  scheduledEndAt
  period
  timezone
  deletedAt
  updatedAt
  createdAt
  tagIds
  taskIds
  itemIds
}

fragment FragmentedPrivateRoutine on PrivateRoutine {
  ...FragmentedBasicPrivateRoutine
}

fragment FragmentedBasicPrivateSearchableRoutine on PrivateSearchableRoutine {
  id
  stationId
  title
  status
  phase
  isPinned
  scheduledStartAt
  scheduledEndAt
  period
  timezone
  deletedAt
  updatedAt
  createdAt
  tagIds
  taskIds
  itemIds
}

fragment FragmentedPrivateSearchableRoutine on PrivateSearchableRoutine {
  ...FragmentedBasicPrivateSearchableRoutine
}
