/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DocumentRouteImport } from './routes/document'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrashRouteImport } from './routes/app.trash'
import { Route as AppRoutinesRouteImport } from './routes/app.routines'
import { Route as AppPlaygroundRouteImport } from './routes/app.playground'
import { Route as AppMaterialViewerRouteImport } from './routes/app.material-viewer'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBlockPackEditorRouteImport } from './routes/app.block-pack-editor'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgetPasswordRouteImport } from './routes/_auth.forgetPassword'
import { Route as AppRoutinesIndexRouteImport } from './routes/app.routines.index'
import { Route as AppMaterialViewerIndexRouteImport } from './routes/app.material-viewer.index'
import { Route as AppDashboardIndexRouteImport } from './routes/app.dashboard.index'
import { Route as AppBlockPackEditorIndexRouteImport } from './routes/app.block-pack-editor.index'
import { Route as AppSettingPreferencesRouteImport } from './routes/app.setting.preferences'
import { Route as AppSettingAccountRouteImport } from './routes/app.setting.account'
import { Route as AppRoutinesStationIdRouteImport } from './routes/app.routines.$stationId'
import { Route as AppMaterialViewerMaterialIdRouteImport } from './routes/app.material-viewer.$materialId'
import { Route as AppBlockPackEditorBlockPackIdRouteImport } from './routes/app.block-pack-editor.$blockPackId'
import { Route as AuthRedirectXRouteImport } from './routes/_auth.redirect.x'
import { Route as AuthRedirectGoogleRouteImport } from './routes/_auth.redirect.google'
import { Route as AuthRedirectErrorRouteImport } from './routes/_auth.redirect.error'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentRoute = DocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoute = AppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialViewerRoute = AppMaterialViewerRouteImport.update({
  id: '/material-viewer',
  path: '/material-viewer',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBlockPackEditorRoute = AppBlockPackEditorRouteImport.update({
  id: '/block-pack-editor',
  path: '/block-pack-editor',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forgetPassword',
  path: '/forgetPassword',
  getParentRoute: () => AuthRoute,
} as any)
const AppRoutinesIndexRoute = AppRoutinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoutinesRoute,
} as any)
const AppMaterialViewerIndexRoute = AppMaterialViewerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMaterialViewerRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppBlockPackEditorIndexRoute = AppBlockPackEditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBlockPackEditorRoute,
} as any)
const AppSettingPreferencesRoute = AppSettingPreferencesRouteImport.update({
  id: '/setting/preferences',
  path: '/setting/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingAccountRoute = AppSettingAccountRouteImport.update({
  id: '/setting/account',
  path: '/setting/account',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesStationIdRoute = AppRoutinesStationIdRouteImport.update({
  id: '/$stationId',
  path: '/$stationId',
  getParentRoute: () => AppRoutinesRoute,
} as any)
const AppMaterialViewerMaterialIdRoute =
  AppMaterialViewerMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => AppMaterialViewerRoute,
  } as any)
const AppBlockPackEditorBlockPackIdRoute =
  AppBlockPackEditorBlockPackIdRouteImport.update({
    id: '/$blockPackId',
    path: '/$blockPackId',
    getParentRoute: () => AppBlockPackEditorRoute,
  } as any)
const AuthRedirectXRoute = AuthRedirectXRouteImport.update({
  id: '/redirect/x',
  path: '/redirect/x',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRedirectGoogleRoute = AuthRedirectGoogleRouteImport.update({
  id: '/redirect/google',
  path: '/redirect/google',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRedirectErrorRoute = AuthRedirectErrorRouteImport.update({
  id: '/redirect/error',
  path: '/redirect/error',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/document': typeof DocumentRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tutorial': typeof TutorialRoute
  '/forgetPassword': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/app/admin': typeof AppAdminRoute
  '/app/block-pack-editor': typeof AppBlockPackEditorRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/material-viewer': typeof AppMaterialViewerRouteWithChildren
  '/app/playground': typeof AppPlaygroundRoute
  '/app/routines': typeof AppRoutinesRouteWithChildren
  '/app/trash': typeof AppTrashRoute
  '/redirect/error': typeof AuthRedirectErrorRoute
  '/redirect/google': typeof AuthRedirectGoogleRoute
  '/redirect/x': typeof AuthRedirectXRoute
  '/app/block-pack-editor/$blockPackId': typeof AppBlockPackEditorBlockPackIdRoute
  '/app/material-viewer/$materialId': typeof AppMaterialViewerMaterialIdRoute
  '/app/routines/$stationId': typeof AppRoutinesStationIdRoute
  '/app/setting/account': typeof AppSettingAccountRoute
  '/app/setting/preferences': typeof AppSettingPreferencesRoute
  '/app/block-pack-editor/': typeof AppBlockPackEditorIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/material-viewer/': typeof AppMaterialViewerIndexRoute
  '/app/routines/': typeof AppRoutinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/document': typeof DocumentRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tutorial': typeof TutorialRoute
  '/forgetPassword': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/app/admin': typeof AppAdminRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/trash': typeof AppTrashRoute
  '/redirect/error': typeof AuthRedirectErrorRoute
  '/redirect/google': typeof AuthRedirectGoogleRoute
  '/redirect/x': typeof AuthRedirectXRoute
  '/app/block-pack-editor/$blockPackId': typeof AppBlockPackEditorBlockPackIdRoute
  '/app/material-viewer/$materialId': typeof AppMaterialViewerMaterialIdRoute
  '/app/routines/$stationId': typeof AppRoutinesStationIdRoute
  '/app/setting/account': typeof AppSettingAccountRoute
  '/app/setting/preferences': typeof AppSettingPreferencesRoute
  '/app/block-pack-editor': typeof AppBlockPackEditorIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/material-viewer': typeof AppMaterialViewerIndexRoute
  '/app/routines': typeof AppRoutinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/document': typeof DocumentRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tutorial': typeof TutorialRoute
  '/_auth/forgetPassword': typeof AuthForgetPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/app/admin': typeof AppAdminRoute
  '/app/block-pack-editor': typeof AppBlockPackEditorRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/material-viewer': typeof AppMaterialViewerRouteWithChildren
  '/app/playground': typeof AppPlaygroundRoute
  '/app/routines': typeof AppRoutinesRouteWithChildren
  '/app/trash': typeof AppTrashRoute
  '/_auth/redirect/error': typeof AuthRedirectErrorRoute
  '/_auth/redirect/google': typeof AuthRedirectGoogleRoute
  '/_auth/redirect/x': typeof AuthRedirectXRoute
  '/app/block-pack-editor/$blockPackId': typeof AppBlockPackEditorBlockPackIdRoute
  '/app/material-viewer/$materialId': typeof AppMaterialViewerMaterialIdRoute
  '/app/routines/$stationId': typeof AppRoutinesStationIdRoute
  '/app/setting/account': typeof AppSettingAccountRoute
  '/app/setting/preferences': typeof AppSettingPreferencesRoute
  '/app/block-pack-editor/': typeof AppBlockPackEditorIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/material-viewer/': typeof AppMaterialViewerIndexRoute
  '/app/routines/': typeof AppRoutinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/document'
    | '/privacy-policy'
    | '/tutorial'
    | '/forgetPassword'
    | '/login'
    | '/register'
    | '/app/admin'
    | '/app/block-pack-editor'
    | '/app/dashboard'
    | '/app/material-viewer'
    | '/app/playground'
    | '/app/routines'
    | '/app/trash'
    | '/redirect/error'
    | '/redirect/google'
    | '/redirect/x'
    | '/app/block-pack-editor/$blockPackId'
    | '/app/material-viewer/$materialId'
    | '/app/routines/$stationId'
    | '/app/setting/account'
    | '/app/setting/preferences'
    | '/app/block-pack-editor/'
    | '/app/dashboard/'
    | '/app/material-viewer/'
    | '/app/routines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/document'
    | '/privacy-policy'
    | '/tutorial'
    | '/forgetPassword'
    | '/login'
    | '/register'
    | '/app/admin'
    | '/app/playground'
    | '/app/trash'
    | '/redirect/error'
    | '/redirect/google'
    | '/redirect/x'
    | '/app/block-pack-editor/$blockPackId'
    | '/app/material-viewer/$materialId'
    | '/app/routines/$stationId'
    | '/app/setting/account'
    | '/app/setting/preferences'
    | '/app/block-pack-editor'
    | '/app/dashboard'
    | '/app/material-viewer'
    | '/app/routines'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/document'
    | '/privacy-policy'
    | '/tutorial'
    | '/_auth/forgetPassword'
    | '/_auth/login'
    | '/_auth/register'
    | '/app/admin'
    | '/app/block-pack-editor'
    | '/app/dashboard'
    | '/app/material-viewer'
    | '/app/playground'
    | '/app/routines'
    | '/app/trash'
    | '/_auth/redirect/error'
    | '/_auth/redirect/google'
    | '/_auth/redirect/x'
    | '/app/block-pack-editor/$blockPackId'
    | '/app/material-viewer/$materialId'
    | '/app/routines/$stationId'
    | '/app/setting/account'
    | '/app/setting/preferences'
    | '/app/block-pack-editor/'
    | '/app/dashboard/'
    | '/app/material-viewer/'
    | '/app/routines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DocumentRoute: typeof DocumentRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TutorialRoute: typeof TutorialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document': {
      id: '/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof DocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/trash': {
      id: '/app/trash'
      path: '/trash'
      fullPath: '/app/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/routines': {
      id: '/app/routines'
      path: '/routines'
      fullPath: '/app/routines'
      preLoaderRoute: typeof AppRoutinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/playground': {
      id: '/app/playground'
      path: '/playground'
      fullPath: '/app/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/material-viewer': {
      id: '/app/material-viewer'
      path: '/material-viewer'
      fullPath: '/app/material-viewer'
      preLoaderRoute: typeof AppMaterialViewerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/block-pack-editor': {
      id: '/app/block-pack-editor'
      path: '/block-pack-editor'
      fullPath: '/app/block-pack-editor'
      preLoaderRoute: typeof AppBlockPackEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgetPassword': {
      id: '/_auth/forgetPassword'
      path: '/forgetPassword'
      fullPath: '/forgetPassword'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/routines/': {
      id: '/app/routines/'
      path: '/'
      fullPath: '/app/routines/'
      preLoaderRoute: typeof AppRoutinesIndexRouteImport
      parentRoute: typeof AppRoutinesRoute
    }
    '/app/material-viewer/': {
      id: '/app/material-viewer/'
      path: '/'
      fullPath: '/app/material-viewer/'
      preLoaderRoute: typeof AppMaterialViewerIndexRouteImport
      parentRoute: typeof AppMaterialViewerRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/block-pack-editor/': {
      id: '/app/block-pack-editor/'
      path: '/'
      fullPath: '/app/block-pack-editor/'
      preLoaderRoute: typeof AppBlockPackEditorIndexRouteImport
      parentRoute: typeof AppBlockPackEditorRoute
    }
    '/app/setting/preferences': {
      id: '/app/setting/preferences'
      path: '/setting/preferences'
      fullPath: '/app/setting/preferences'
      preLoaderRoute: typeof AppSettingPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setting/account': {
      id: '/app/setting/account'
      path: '/setting/account'
      fullPath: '/app/setting/account'
      preLoaderRoute: typeof AppSettingAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/routines/$stationId': {
      id: '/app/routines/$stationId'
      path: '/$stationId'
      fullPath: '/app/routines/$stationId'
      preLoaderRoute: typeof AppRoutinesStationIdRouteImport
      parentRoute: typeof AppRoutinesRoute
    }
    '/app/material-viewer/$materialId': {
      id: '/app/material-viewer/$materialId'
      path: '/$materialId'
      fullPath: '/app/material-viewer/$materialId'
      preLoaderRoute: typeof AppMaterialViewerMaterialIdRouteImport
      parentRoute: typeof AppMaterialViewerRoute
    }
    '/app/block-pack-editor/$blockPackId': {
      id: '/app/block-pack-editor/$blockPackId'
      path: '/$blockPackId'
      fullPath: '/app/block-pack-editor/$blockPackId'
      preLoaderRoute: typeof AppBlockPackEditorBlockPackIdRouteImport
      parentRoute: typeof AppBlockPackEditorRoute
    }
    '/_auth/redirect/x': {
      id: '/_auth/redirect/x'
      path: '/redirect/x'
      fullPath: '/redirect/x'
      preLoaderRoute: typeof AuthRedirectXRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/redirect/google': {
      id: '/_auth/redirect/google'
      path: '/redirect/google'
      fullPath: '/redirect/google'
      preLoaderRoute: typeof AuthRedirectGoogleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/redirect/error': {
      id: '/_auth/redirect/error'
      path: '/redirect/error'
      fullPath: '/redirect/error'
      preLoaderRoute: typeof AuthRedirectErrorRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRedirectErrorRoute: typeof AuthRedirectErrorRoute
  AuthRedirectGoogleRoute: typeof AuthRedirectGoogleRoute
  AuthRedirectXRoute: typeof AuthRedirectXRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRedirectErrorRoute: AuthRedirectErrorRoute,
  AuthRedirectGoogleRoute: AuthRedirectGoogleRoute,
  AuthRedirectXRoute: AuthRedirectXRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppBlockPackEditorRouteChildren {
  AppBlockPackEditorBlockPackIdRoute: typeof AppBlockPackEditorBlockPackIdRoute
  AppBlockPackEditorIndexRoute: typeof AppBlockPackEditorIndexRoute
}

const AppBlockPackEditorRouteChildren: AppBlockPackEditorRouteChildren = {
  AppBlockPackEditorBlockPackIdRoute: AppBlockPackEditorBlockPackIdRoute,
  AppBlockPackEditorIndexRoute: AppBlockPackEditorIndexRoute,
}

const AppBlockPackEditorRouteWithChildren =
  AppBlockPackEditorRoute._addFileChildren(AppBlockPackEditorRouteChildren)

interface AppDashboardRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppMaterialViewerRouteChildren {
  AppMaterialViewerMaterialIdRoute: typeof AppMaterialViewerMaterialIdRoute
  AppMaterialViewerIndexRoute: typeof AppMaterialViewerIndexRoute
}

const AppMaterialViewerRouteChildren: AppMaterialViewerRouteChildren = {
  AppMaterialViewerMaterialIdRoute: AppMaterialViewerMaterialIdRoute,
  AppMaterialViewerIndexRoute: AppMaterialViewerIndexRoute,
}

const AppMaterialViewerRouteWithChildren =
  AppMaterialViewerRoute._addFileChildren(AppMaterialViewerRouteChildren)

interface AppRoutinesRouteChildren {
  AppRoutinesStationIdRoute: typeof AppRoutinesStationIdRoute
  AppRoutinesIndexRoute: typeof AppRoutinesIndexRoute
}

const AppRoutinesRouteChildren: AppRoutinesRouteChildren = {
  AppRoutinesStationIdRoute: AppRoutinesStationIdRoute,
  AppRoutinesIndexRoute: AppRoutinesIndexRoute,
}

const AppRoutinesRouteWithChildren = AppRoutinesRoute._addFileChildren(
  AppRoutinesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBlockPackEditorRoute: typeof AppBlockPackEditorRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppMaterialViewerRoute: typeof AppMaterialViewerRouteWithChildren
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppRoutinesRoute: typeof AppRoutinesRouteWithChildren
  AppTrashRoute: typeof AppTrashRoute
  AppSettingAccountRoute: typeof AppSettingAccountRoute
  AppSettingPreferencesRoute: typeof AppSettingPreferencesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBlockPackEditorRoute: AppBlockPackEditorRouteWithChildren,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppMaterialViewerRoute: AppMaterialViewerRouteWithChildren,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppRoutinesRoute: AppRoutinesRouteWithChildren,
  AppTrashRoute: AppTrashRoute,
  AppSettingAccountRoute: AppSettingAccountRoute,
  AppSettingPreferencesRoute: AppSettingPreferencesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DocumentRoute: DocumentRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TutorialRoute: TutorialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
